---
title: "Circumferences and Diameters"
author: "Takari Primary School, Year 4/5"
format: html
self-contained: true
---

```{r}
#| message: false
library(googlesheets4)
library(dplyr)
library(ggplot2)
library(gt)

SHEET_URL = "https://docs.google.com/spreadsheets/d/1bksGyGA3EwGqtk28JD_4kEl3sccoPlKQ05yoW6J4ZK0/edit#gid=1380425156"
```

```{r}
#| message: true
circles_data <- read_sheet(SHEET_URL,
                           col_names = c("Group", 
                                         "Object", "Diameter", "Circumference",
                                         "Difficulty"),
                           col_types = "cciii",
                           range = "B2:F",
                           skip = 1) |> 
  mutate(Ratio = Circumference/Diameter)
```

```{r}
circles_data |> 
  gt()
```

```{r}
circles_data |> 
  count(Object) |> 
  gt()
```


```{r}
circles_data |> 
  ggplot() +
  aes(x = Diameter) +
  geom_dotplot(binwidth = 10, fill = "blue") +
  labs(title = "Dotplot of Circle Diameters", x = "Diameter (mm)") +
  scale_y_continuous(NULL, breaks = NULL) +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))
```


```{r}
circles_data |> 
  ggplot() +
  aes(x = Circumference) +
  geom_dotplot(binwidth = 30, fill = "green") +
  labs(title = "Dotplot of Circle Circumferences", x = "Circumference (mm)") +
  scale_y_continuous(NULL, breaks = NULL) +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
circles_data |> 
  ggplot() +
  aes(x = Ratio) +
  geom_histogram(bins = 30, fill = "grey") +
  geom_vline(xintercept = pi, colour = "red", linewidth = 1, linetype = "dotted") +
  labs(title = "Histogram of Circumference/Diameter", x = "Ratio", y = "Count") +
  #scale_y_continuous(NULL, breaks = NULL) +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))
```


```{r}
circles_data |> 
  ggplot() +
  aes(x = Diameter, y = Circumference) +
  geom_jitter(mapping = aes(colour = Object), size = 5, alpha = 0.5) +
  geom_smooth(method = "lm", formula = "y ~ x", se = FALSE, colour = "black") +
  lims(x = c(0,270), y = c(0,800)) +
  labs(title = "Plot of Circumference vs Diameter", x = "Diameter (mm)", y = "Circumference (mm)") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))
```



```{r}
circles_data |> 
  ggplot() +
  aes(x = Ratio) +
  geom_density() +
  geom_vline(xintercept = pi, colour = "red", linewidth = 1, linetype = "dotted") +
  labs(title = "Density of Circumference/Diameter", x = "Ratio", y = "Density") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))
```






